[theme]
primaryColor = "#2167d5"
backgroundColor = "#f4f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#17283d"
font = "sans serif"

[server]
headless = true
maxUploadSize = 20

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = "stacktrace"
